# Documentation Auto-Synthesis Configuration
# Controls which documentation updates are applied automatically vs suggested

auto_apply:
  # Safe updates that can be applied automatically
  epic_status_updates: true          # Update Epic completion status
  token_limit_monitoring: true       # Check and report token limits  
  workflow_status_updates: true      # Update AI workflow documentation
  progress_json_updates: true        # Update progress tracking
  
  # Threshold settings
  claude_md_token_warning: 4500      # Warn when CLAUDE.md approaches limit
  max_auto_changes_per_pr: 5         # Limit auto-changes per PR

suggest_only:
  # Complex changes that need human review
  new_api_documentation: true        # New API endpoints or major changes
  new_features: true                 # Completely new features
  architecture_changes: true         # Major structural changes
  external_dependencies: true        # New external integrations

safety_rails:
  # Prevent inappropriate auto-changes
  require_pr_context: true           # Only run on PRs, not direct pushes
  skip_if_conflicts: true            # Skip if file has merge conflicts
  backup_before_changes: true        # Create backup of modified files
  human_review_threshold: 3          # Require review if >3 auto-changes

# Patterns to detect for auto-updates
patterns:
  epic_completion:
    - "Epic.*Complete"
    - "Epic.*finished"
    - "All.*issues.*closed"
  
  workflow_additions:
    - "github/workflows"
    - "claude"
    - "AI"
    - "@claude"
  
  api_changes:
    - "def.*endpoint"
    - "router\\."
    - "FastAPI"
    - "POST|GET|PUT|DELETE.*/"