"""Pydantic schemas for API requests and responses."""

from .base import (  # Archetype schemas; Build schemas; Enhancement schemas; Import log schemas; Power schemas; Powerset schemas
    Archetype,
    ArchetypeBase,
    ArchetypeCreate,
    ArchetypeUpdate,
    ArchetypeWithPowersets,
    Build,
    BuildBase,
    BuildCreate,
    BuildEnhancement,
    BuildEnhancementBase,
    BuildEnhancementCreate,
    BuildPower,
    BuildPowerBase,
    BuildPowerCreate,
    BuildStats,
    BuildUpdate,
    BuildWithDetails,
    Enhancement,
    EnhancementBase,
    EnhancementCreate,
    EnhancementSet,
    EnhancementSetBase,
    EnhancementSetCreate,
    EnhancementSetUpdate,
    EnhancementSetWithDetails,
    EnhancementUpdate,
    ImportLog,
    ImportLogBase,
    ImportLogCreate,
    Power,
    PowerBase,
    PowerCreate,
    Powerset,
    PowersetBase,
    PowersetCreate,
    PowersetUpdate,
    PowersetWithPowers,
    PowerUpdate,
    PowerWithDetails,
)
from .calculations import (  # Enums; Build totals; Damage calculation; Defense calculation; Effect models; Enhancement calculation; Error handling; Constants; Resistance calculation
    ArchetypeEnum,
    BuildTotalsRequest,
    BuildTotalsResponse,
    DamageCalculationRequest,
    DamageCalculationResponse,
    DamageMathModeEnum,
    DamageReturnModeEnum,
    DamageTypeEnum,
    DefenseBonusInput,
    DefenseCalculationRequest,
    DefenseCalculationResponse,
    DefenseTypeEnum,
    EffectRequest,
    EnhancementSlotRequest,
    ErrorResponse,
    GameConstantsResponse,
    PowerTypeEnum,
    ProcCalculationRequest,
    ProcCalculationResponse,
    ResistanceBonusInput,
    ResistanceCalculationRequest,
    ResistanceCalculationResponse,
    ResistanceTypeEnum,
)

__all__ = [
    # Base schemas - Archetypes
    "Archetype",
    "ArchetypeBase",
    "ArchetypeCreate",
    "ArchetypeUpdate",
    "ArchetypeWithPowersets",
    # Base schemas - Builds
    "Build",
    "BuildBase",
    "BuildCreate",
    "BuildEnhancement",
    "BuildEnhancementBase",
    "BuildEnhancementCreate",
    "BuildPower",
    "BuildPowerBase",
    "BuildPowerCreate",
    "BuildStats",
    "BuildUpdate",
    "BuildWithDetails",
    # Base schemas - Enhancements
    "Enhancement",
    "EnhancementBase",
    "EnhancementCreate",
    "EnhancementSet",
    "EnhancementSetBase",
    "EnhancementSetCreate",
    "EnhancementSetUpdate",
    "EnhancementSetWithDetails",
    "EnhancementUpdate",
    # Base schemas - Import logs
    "ImportLog",
    "ImportLogBase",
    "ImportLogCreate",
    # Base schemas - Powers
    "Power",
    "PowerBase",
    "PowerCreate",
    "PowerUpdate",
    "PowerWithDetails",
    # Base schemas - Powersets
    "Powerset",
    "PowersetBase",
    "PowersetCreate",
    "PowersetUpdate",
    "PowersetWithPowers",
    # Calculation schemas - Enums
    "ArchetypeEnum",
    "DamageTypeEnum",
    "DefenseTypeEnum",
    "ResistanceTypeEnum",
    "PowerTypeEnum",
    "DamageMathModeEnum",
    "DamageReturnModeEnum",
    # Calculation schemas - Effect models
    "EffectRequest",
    # Calculation schemas - Damage calculation
    "DamageCalculationRequest",
    "DamageCalculationResponse",
    # Calculation schemas - Defense calculation
    "DefenseBonusInput",
    "DefenseCalculationRequest",
    "DefenseCalculationResponse",
    # Calculation schemas - Resistance calculation
    "ResistanceBonusInput",
    "ResistanceCalculationRequest",
    "ResistanceCalculationResponse",
    # Calculation schemas - Build totals
    "BuildTotalsRequest",
    "BuildTotalsResponse",
    # Calculation schemas - Constants
    "GameConstantsResponse",
    # Calculation schemas - Enhancement calculation
    "EnhancementSlotRequest",
    "ProcCalculationRequest",
    "ProcCalculationResponse",
    # Calculation schemas - Error handling
    "ErrorResponse",
]
