name: Claude Code Integration

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude-code:
    if: |
      (github.event.issue.pull_request && contains(github.event.comment.body, '@claude')) ||
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
      - name: Process Request
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          mode: 'respond'
          context: |
            You are assisting with the {{PROJECT_NAME}} project.
            Key context:
            - Follow the patterns in CLAUDE.md
            - Check .claude/shared/memory/ for project context
            - Use the task runner: just
            - Important: Use fd instead of find, trash instead of rm -rf
            
      - name: Post Response
        if: steps.claude.outputs.response
        uses: actions/github-script@v7
        with:
          script: |
            const response = `${{ steps.claude.outputs.response }}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: response
            });

  claude-code-review:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
      - name: Analyze Code Context
        id: analyze
        run: |
          # Get the file and line number from the comment
          FILE_PATH="${{ github.event.comment.path }}"
          LINE_NUMBER="${{ github.event.comment.line }}"
          
          # Extract surrounding context
          if [ -f "$FILE_PATH" ]; then
            head -n $((LINE_NUMBER + 10)) "$FILE_PATH" | tail -n 21 > context.txt
            echo "context<<EOF" >> $GITHUB_OUTPUT
            cat context.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
      - name: Generate Code Suggestion
        id: suggest
        uses: anthropics/claude-code-action@v1
        with:
          mode: 'code-review'
          context: |
            File: ${{ github.event.comment.path }}
            Line: ${{ github.event.comment.line }}
            Comment: ${{ github.event.comment.body }}
            
            Code context:
            ${{ steps.analyze.outputs.context }}
            
            Provide specific code improvements or answer the question.
            Follow project standards and conventions.
            
      - name: Reply to Comment
        if: steps.suggest.outputs.suggestion
        uses: actions/github-script@v7
        with:
          script: |
            const suggestion = `${{ steps.suggest.outputs.suggestion }}`;
            
            github.rest.pulls.createReplyForReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              comment_id: context.payload.comment.id,
              body: suggestion
            });