name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Automatic PR Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run custom Claude integration for PR review
          bash .github/scripts/claude_wrapper.sh \
            --prompt "Please review pull request #${{ github.event.pull_request.number }} and provide comprehensive feedback.

            Repository: ${{ github.repository }}
            PR Title: ${{ github.event.pull_request.title }}
            
            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed
            - City of Heroes domain accuracy (for game mechanics)

            Provide constructive feedback with specific suggestions for improvement.
            Mention specific files and line numbers where applicable.
            
            Format your response as a helpful PR review comment." \
            --timeout 30 \
            --pr ${{ github.event.pull_request.number }} \
            --post-comment
