name: Documentation Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  doc-impact-review:
    name: Review Documentation Impact
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**/*.py
            frontend/**/*.{js,ts,jsx,tsx}
            **/*.md
            backend/pyproject.toml
            frontend/package.json
            docker-compose.yml
            Dockerfile
            justfile
            .claude/**/*.md
            .github/workflows/*.yml
            
      - name: Set up Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Documentation Review with Claude
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run custom Claude integration
          bash .github/scripts/claude_wrapper.sh \
            --prompt "Review the changes in PR #${{ github.event.pull_request.number }} and analyze documentation impact.
            
            Changed files: ${{ steps.changed-files.outputs.all_changed_files }}
            
            Please provide:
            1. A concise analysis of which documentation might need updates based on the changes
            2. Specific suggestions for documentation that should be updated
            3. Check if any README files reference changed/deleted files
            4. Verify CLAUDE.md token limit compliance if it was changed
            
            Focus areas:
            - If workflows changed: Check .github/workflows/README.md accuracy
            - If API files changed: Suggest API documentation updates
            - If models changed: Suggest database documentation updates
            - If justfile changed: Suggest command documentation updates
            - If .claude/ files changed: Check context system documentation
            
            Format your response as a PR comment with:
            - Summary of documentation impact
            - Checklist of recommended updates
            - Any warnings about stale references
            
            Keep the review concise and actionable." \
            --timeout 10 \
            --pr ${{ github.event.pull_request.number }} \
            --post-comment