name: Documentation Synthesis

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to process'
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-changes:
    runs-on: ubuntu-latest
    outputs:
      needs_doc_update: ${{ steps.check.outputs.needs_update }}
      changed_files: ${{ steps.check.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**/*.py
            frontend/**/*.{js,ts,jsx,tsx}
            **/*.md
            backend/pyproject.toml
            frontend/package.json
            docker-compose.yml
            Dockerfile
            justfile
            .claude/**/*.md
            
      - name: Check if docs need update
        id: check
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

  synthesize-docs:
    needs: analyze-changes
    if: needs.analyze-changes.outputs.needs_doc_update == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install anthropic pyyaml tiktoken
          
      - name: Analyze code changes for documentation
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python -c "
          import os
          import anthropic
          from pathlib import Path
          
          client = anthropic.Anthropic()
          
          # Read changed files
          changed_files = '''${{ needs.analyze-changes.outputs.changed_files }}'''.split()
          
          # Read current CLAUDE.md for context
          claude_md = ''
          try:
              with open('CLAUDE.md', 'r') as f:
                  claude_md = f.read()
          except:
              pass
          
          # Analyze changes and suggest doc updates
          file_contents = {}
          for file_path in changed_files[:10]:  # Limit to first 10 files
              try:
                  with open(file_path, 'r') as f:
                      content = f.read()[:2000]  # First 2k chars
                      file_contents[file_path] = content
              except:
                  pass
          
          if not file_contents:
              exit(0)
          
          prompt = f'''Analyze these code changes for the Mids Hero Web project and suggest documentation updates.

Current CLAUDE.md (first 3000 chars):
{claude_md[:3000]}

Changed Files:
{chr(10).join([f\"{path}:\n{content[:500]}...\" for path, content in file_contents.items()])}

Please suggest:
1. Updates needed for README.md (if API changes, new features, setup changes)
2. Updates needed for CLAUDE.md (if workflow changes, new commands, context changes)
3. Updates needed for .claude/epics/ files (if epic progress changes)
4. New documentation needed (if new major features)

Focus on:
- API endpoint changes (update API documentation)
- New just commands (update quick-commands.md)
- Database model changes (update database-design.md)
- New Epic progress (update epic status)
- Docker/deployment changes (update setup instructions)

Provide specific suggestions in markdown format:'''
          
          response = client.messages.create(
              model='claude-3-5-sonnet-20241022',
              max_tokens=2000,
              messages=[{'role': 'user', 'content': prompt}]
          )
          
          suggestions = response.content[0].text
          
          with open('doc_suggestions.md', 'w') as f:
              f.write(suggestions)
          "
          
      - name: Check if documentation updates are needed
        id: doc-check
        run: |
          if [ -f "doc_suggestions.md" ] && [ -s "doc_suggestions.md" ]; then
            echo "has_suggestions=true" >> $GITHUB_OUTPUT
          else
            echo "has_suggestions=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create documentation PR comment
        if: steps.doc-check.outputs.has_suggestions == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const suggestions = fs.readFileSync('doc_suggestions.md', 'utf8');
            
            const comment = `## 📚 Documentation Update Suggestions

The following code changes may require documentation updates:

${suggestions}

### Action Items:
- [ ] Review suggested documentation updates
- [ ] Update relevant documentation files
- [ ] Ensure CLAUDE.md stays under 5k tokens
- [ ] Update epic progress if applicable

---
*Generated by automated documentation analysis*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });