name: Documentation Synthesis

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches: [main, develop, test/*]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-changes:
    runs-on: ubuntu-latest
    outputs:
      needs_doc_update: ${{ steps.check.outputs.needs_update }}
      changed_files: ${{ steps.check.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**/*.py
            frontend/**/*.{js,ts,jsx,tsx}
            **/*.md
            backend/pyproject.toml
            frontend/package.json
            docker-compose.yml
            Dockerfile
            justfile
            .claude/**/*.md
            
      - name: Check if docs need update
        id: check
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

  synthesize-docs:
    needs: analyze-changes
    if: needs.analyze-changes.outputs.needs_doc_update == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          
      - name: Documentation Analysis with Claude
        uses: anthropics/claude-code-action@v1.2.0
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "15"
          direct_prompt: |
            Analyze code changes for the Mids Hero Web project and provide documentation suggestions.
            
            Changed files: ${{ needs.analyze-changes.outputs.changed_files }}
            
            Tasks:
            1. Review the changed files and determine what documentation updates are needed
            2. Focus on:
               - API endpoint changes (suggest API documentation updates)
               - New just commands (suggest quick-commands.md updates)
               - Database model changes (suggest database-design.md updates)
               - Epic progress changes (suggest epic status updates)
               - Docker/deployment changes (suggest setup instruction updates)
            3. Create a markdown report with specific documentation suggestions
            4. If this is a pull request, post the suggestions as a comment
            5. Ensure suggestions consider CLAUDE.md token limits (must stay under 5K)
            
            Output format:
            - Clear markdown sections for each type of documentation that needs updating
            - Specific recommendations for what to add/change
            - Priority indicators for critical updates
            
            Event type: ${{ github.event_name }}
            PR number (if applicable): ${{ github.event.pull_request.number }}